cad_mesher:
  #read param
  use_sim_time: true
  grt_available: false 
  use_odom_prior: true 
  read_offline_pcd: false
  dataset: 1  # Means using KITTI dataset
  max_steps: 10000
  save_mesh_map: true
  save_raw_point_clouds: true
  #register param
  range_max: 70.0
  range_min: 1.0
  register_times: 2
  cross_overlap: true
  cross_cell_overlap_length: 2
  num_margin_old_cell: -1 # do not margin old cells, the cell-based map will have implicit loop closure effect.
  point2mesh: true
  residual_combination: true
  #visualize parameter
  meshing_tsdf: false
  full_cover: true  # so that there is no gap between cells.
  visualisation_type: 3
  #gp param
  num_thread: 15 #8
  grid: 1.6 #精度:1.6 建图:1.5
  min_points_num_to_gp: 11 #05:5 建图:8
  num_test: 6 #一个体素内GP点的数量 6:05 建图:10
  
  variance_register: 0.60
  variance_map_update: 0.50
  variance_map_show: 1.00
  variance_min: 1.36
  variance_sensor: 0.02
  
  test_param:  0
  
  sliding_window_size: 5
  scan_number: 64
  use_adaptive_kd: true
  use_curvature: true
  use_curvature_weight: false
  use_global_ground_contraint: true
  use_local_ground_contraint: false
  skip_map_glb_pub: 5
  ground_number_threshold: 15
  use_dynamic_removal: true
  stable_threshold: 0.97
  p_hit: 0.7
  p_miss: 0.4



